apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: pyflink-helloworld
  namespace: csa-ssb
spec:
  image: nexus.dlee1.cldr.example:9999/pvcds/pyflink-kafka:19.2-csaop1.2.0-b27 #for TaskManager
  flinkVersion: v1_19
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
  serviceAccount: flink
  mode: native
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
    podTemplate:
      apiVersion: v1
      kind: Pod
      metadata:
        name: pyflink-helloworld
      spec:
        serviceAccountName: flink  # Service account for the job
        initContainers:
          - name: create-scripts-directory
            image: alpine:latest
            command:
              - /bin/sh
              - -c
              - |
                # Ensure the directory exists before mounting the ConfigMap
                mkdir -p /opt/flink/scripts
            volumeMounts:
              - name: pyflink-scripts
                mountPath: /opt/flink/scripts
        containers:
          - name: flink-main-container
            image: nexus.dlee1.cldr.example:9999/pvcds/pyflink-kafka:19.2-csaop1.2.0-b27
            volumeMounts:
              - name: pyflink-scripts
                mountPath: /opt/flink/scripts  # Mount Python script to /opt/flink/scripts
        volumes:
          - name: pyflink-scripts
            configMap:
              name: pyflink-hello-world-script
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/pyflink-kafka.jar
    #jarURI: "local:///opt/flink/opt/flink-python.jar,local:///opt/flink/usrlib/pyflink-kafka.jar"
    entryClass: "org.apache.flink.client.python.PythonDriver"
    args: ["-pyclientexec", "/usr/bin/python3", "-py", "/opt/flink/scripts/pyflink-hello-world.py"]
    parallelism: 1
    upgradeMode: stateless
